from NumPyCreator import NumPyCreator

npc = NumPyCreator()
# print(npc.from_list([3, 6, 2 , 4]))
print("from list:")
print(npc.from_list([[1,2,3],[6,3,4]]))
print(npc.from_list([[1,2,3],[6,4]]))
print(npc.from_list([[1,2,3],['a','b','c'],[6,4,7]]))
print(npc.from_list(((1,2),(3,4))))
print("from tuple:")
print(npc.from_tuple(("a", "b", "c")))
print(npc.from_tuple(["a", "b", "c"]))
print("from iterable")
print(npc.from_iterable(range(5)))
print(npc.from_iterable(5))
print("from shape:")
shape=(3,5)
print(npc.from_shape(shape))
print("random:")
print(npc.random(shape))
print(npc.random((0,1)))
print(npc.random(5))